# Project requirements (PEP 518, https://python-poetry.org)


[project]
name = "jupyterhub-monitoring"
version = "2.4.0"
description = "Monitoring and reporting scripts for JupyterHub"
license = "Apache-2.0"
authors = [{ name = "Brian Aydemir", email = "baydemir@morgridge.org" }]
dynamic = ["dependencies"]


[project.urls]
repository = "https://github.com/brianaydemir/jupyterhub-monitoring"


[project.scripts]
create-es-api-key = "app.cli.create_es_api_key:main"
delete-es-api-key = "app.cli.delete_es_api_key:main"
get-es-docs = "app.cli.get_es_docs:main"
get-new-activity = "app.cli.get_new_activity:main"
get-new-users = "app.cli.get_new_users:main"
list-es-api-keys = "app.cli.list_es_api_keys:main"
push-servers = "app.cli.push_servers:main"


#---------------------------------------------------------------------------


[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]


[tool.black]
line-length = 96


[tool.isort]
line_length = 96
profile = "black"


[tool.mypy]
# Reference: https://mypy.readthedocs.io/en/stable/config_file.html

# Import discovery
explicit_package_bases = true
follow_untyped_imports = true

# Untyped definitions and calls
check_untyped_defs = true

# Configuring warnings
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true

# Configuring error messages
pretty = true

# Incremental mode
sqlite_cache = true


[tool.poetry]
package-mode = true
packages = [{ include = "app" }]


[tool.poetry.dependencies]
python = "^3.14"
elasticsearch = "~9.3"
pytimeparse2 = "~1.7"
requests = "~2.32"
jinja2 = "~3.1"
tabulate = "~0.9"


[tool.poetry.group.dev.dependencies]
bandit = "~1.9"
black = "~26.3"
isort = "~8.0"
mdformat = "~1.0"
mypy = "~1.19"
pre-commit = "~4.5"
pylint = "~4.0"
pyright = "~1.1"
sphinx = "~9.1"
shibuya = "~2026.1"
toml-cli = "~0.8"
typos = "~1.44"
mdit-py-plugins = "~0.5"
mdformat-gfm = "~1.0"
mdformat-gfm-alerts = "~2.0"


[tool.pyright]
typeCheckingMode = "strict"

# Be more forgiving.
reportMissingTypeStubs = "none"

# Be less forgiving.
deprecateTypingAliases = true
reportImplicitOverride = true
reportImplicitStringConcatenation = true
reportPropertyTypeMismatch = true
reportUnnecessaryTypeIgnoreComment = true
reportUnreachable = true


[tool.pylint.messages-control]
max-line-length = 96
enable = [
    "useless-suppression",
]
disable = [
    "duplicate-code",
    "line-too-long",
    "too-many-arguments",
    "too-many-positional-arguments",
]
