# Project requirements (PEP 518, https://python-poetry.org)


[project]
name = "jupyterhub-monitoring"
version = "2.0.1"
description = "Monitoring and reporting scripts for JupyterHub"
license = "Apache-2.0"
authors = [{ name = "Brian Aydemir", email = "baydemir@morgridge.org" }]
dynamic = ["dependencies"]


[project.urls]
repository = "https://github.com/brianaydemir/jupyterhub-monitoring"


[project.scripts]
create-es-api-key = "app.create_es_api_key:main"
delete-es-api-key = "app.delete_es_api_key:main"
get-es-docs = "app.get_es_docs:main"
get-new-users = "app.get_new_users:main"
list-es-api-keys = "app.list_es_api_keys:main"
push-servers = "app.push_servers:main"
send-email = "app.send_email:main"


#---------------------------------------------------------------------------


[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]


[tool.black]
line-length = 88
target-version = ["py314"]


[tool.isort]
line_length = 88
profile = "black"


[tool.mypy]
# Import discovery
explicit_package_bases = true
follow_untyped_imports = true

# Untyped definitions and calls
check_untyped_defs = true

# Configuring warnings
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true

# Configuring error messages
pretty = true

# Incremental mode
sqlite_cache = true


[tool.poetry]
package-mode = true
packages = [{ include = "app" }]


[tool.poetry.dependencies]
python         = "^3.14"
elasticsearch  = "~9.3"
humanize       = "~4.15"
pytimeparse2   = "~1.7"
requests       = "~2.32"


[tool.poetry.group.dev.dependencies]
bandit      = "~1.9"
black       = "~26.1"
isort       = "~8.0"
mypy        = "~1.19"
pre-commit  = "~4.5"
pylint      = "~4.0"
toml-cli    = "~0.8"
typos       = "~1.43"


[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.0.0"


[tool.pylint.messages-control]
max-line-length = 88
disable = "duplicate-code,invalid-name,line-too-long,missing-class-docstring,missing-function-docstring,too-many-arguments,too-many-locals,too-many-positional-arguments"
